# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import time
import random
import os


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1080, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1080, 720))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        
        self.url = None
        self.state = False
        self.count = 0
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1080, 720))
        self.centralwidget.setMaximumSize(QtCore.QSize(1080, 720))
        self.centralwidget.setObjectName("centralwidget")
        
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1080, 720))
        self.label.setMinimumSize(QtCore.QSize(1080, 720))
        self.label.setMaximumSize(QtCore.QSize(1080, 720))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(os.path.join(os.getcwd(),"Artboard 1 copy 3@2x.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        
        self.refreshCount = QtWidgets.QLCDNumber(self.centralwidget)
        self.refreshCount.setGeometry(QtCore.QRect(263, 530, 81, 71))
        self.refreshCount.setAutoFillBackground(False)
        self.refreshCount.setLineWidth(0)
        self.refreshCount.setMidLineWidth(0)
        self.refreshCount.setSmallDecimalPoint(False)
        self.refreshCount.setDigitCount(4)
        self.refreshCount.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.refreshCount.setProperty("value", 0.0)
        self.refreshCount.setObjectName("refreshCount")
        
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(470, 480, 131, 41))
        self.start.setAutoFillBackground(False)
        self.start.setText("")
        self.start.setAutoDefault(False)
        self.start.setDefault(False)
        self.start.setFlat(True)
        self.start.setObjectName("start")
        
        self.end = QtWidgets.QPushButton(self.centralwidget)
        self.end.setGeometry(QtCore.QRect(480, 560, 131, 41))
        self.end.setAutoFillBackground(False)
        self.end.setText("")
        self.end.setAutoDefault(False)
        self.end.setDefault(False)
        self.end.setFlat(True)
        self.end.setObjectName("end")
        
        self.automatic = QtWidgets.QPushButton(self.centralwidget)
        self.automatic.setGeometry(QtCore.QRect(740, 540, 61, 51))
        self.automatic.setAutoFillBackground(False)
        self.automatic.setText("")
        self.automatic.setAutoDefault(False)
        self.automatic.setDefault(False)
        self.automatic.setFlat(True)
        self.automatic.setObjectName("automatic")
        
        self.manual = QtWidgets.QPushButton(self.centralwidget)
        self.manual.setGeometry(QtCore.QRect(890, 540, 68, 51))
        self.manual.setAutoFillBackground(False)
        self.manual.setText("")
        self.manual.setAutoDefault(False)
        self.manual.setDefault(False)
        self.manual.setFlat(True)
        self.manual.setObjectName("manual")
        
        self.textLink = QtWidgets.QPushButton(self.centralwidget)
        self.textLink.setGeometry(QtCore.QRect(278, 400, 524, 31))
        self.textLink.setAutoFillBackground(False)
        self.textLink.setText("www.example_url.com")
        self.textLink.setAutoDefault(False)
        self.textLink.setDefault(False)
        self.textLink.setFlat(True)
        self.textLink.setObjectName("textBrowser")
        
        # Create textbox
        # self.textbox = QtWidgets.QLineEdit(self.centralwidget)
        # self.textbox.setGeometry(QtCore.QRect(278, 400, 324, 31))
        # self.textbox.setAutoFillBackground(False)
        # self.textbox.move(20, 20)
        # self.textbox.resize(280,40)
        
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(1010, 16, 31, 31))
        self.exit.setAutoFillBackground(False)
        self.exit.setText("")
        self.exit.setAutoDefault(False)
        self.exit.setDefault(False)
        self.exit.setFlat(True)
        self.exit.setObjectName("exit")
        
        self.pause = QtWidgets.QPushButton(self.centralwidget)
        self.pause.setGeometry(QtCore.QRect(952, 16, 31, 31))
        self.pause.setAutoFillBackground(False)
        self.pause.setText("")
        self.pause.setAutoDefault(False)
        self.pause.setDefault(False)
        self.pause.setFlat(True)
        self.pause.setObjectName("pause")
        
        self.start.clicked.connect(self.start_clicked)
        self.end.clicked.connect(self.end_clicked)
        self.automatic.clicked.connect(self.automatic_clicked)
        self.manual.clicked.connect(self.manual_clicked)
        self.exit.clicked.connect(self.exit_clicked)
        self.pause.clicked.connect(self.pause_clicked)
        self.textLink.clicked.connect(self.takeinputs)
        # self.textbox.textChanged.connect(self.pause_clicked)
            
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    
    def start_clicked(self):
        self.refresh_tab()
        print("start")
        
    def end_clicked(self):
        print("end")
        
    def automatic_clicked(self):
        print("automatic")
        
    def manual_clicked(self):
        self.takeManualInputs()
        print("manual")
        
    def exit_clicked(self):
        print("exit")
        sys.exit(app.exec_())
        
    def pause_clicked(self):
        print("pause")
    
    # def tex
        
    # def textLink_clicked(self):
    #     print("textLink")
    #     self.takeinputs
    
    def refresh_tab(self):
        # sec = random.randint(2, 10)
        # self.url = 'www.google.com'
        self.count = int(self.count)
        if self.url is not None:
            while self.count>0:
                browser= webdriver.Chrome(ChromeDriverManager().install())
                print("Refreshing URL: ",self.url)
                browser.get('https://'+self.url)
                browser.refresh()
                self.refreshCount.display(self.refreshCount.value() - 1)
                time.sleep(2)
                self.count-=1
    
    def takeinputs(self):
        name, done1 = QtWidgets.QInputDialog.getText(
            MainWindow, 'Enter the website', 'URL:')
        if done1:
            self.url = name
            print("URL received: "+'https://'+self.url)
            self.textLink.setText(self.url)
            
    def takeManualInputs(self):
        name, done1 = QtWidgets.QInputDialog.getText(
            MainWindow, 'How many times', 'Count:')
        if done1:
            self.count = name
            self.refreshCount.setProperty("value", int(self.count))
    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("AUTOLANCER", "AUTOLANCER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
